version: "3.8"
services:
  api:
    container_name: api
    command: sh -c 'npm install && npm run start:dev'
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/api

  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root

volumes:
  postgres:
